### ISSUE TITLE
FockBasis_Example_1.m (v1.0) does not terminate.

### ISSUE THREAD

**Issue by alexpiti** [Filippos-Dakis/Wigner-Function-Quantum-Optics#1]
Hey there. I don't understand what this does, but the **script FockBasis_Example_1.m** (v1.0) does not terminate within reasonable time (e.g. ~60 seconds). It seems to get stuck after line 120, in WignerFunction? I am using MATLAB 2022b.

PS -- It's a good idea to mention (in the GitHub Readme and/or the in function/script header) the MATLAB version this was developed on and also what it produces (e.g. two figures) and how long it typically takes to execute (e.g. on regular laptop/desktop).

**Comment by Filippos-Dakis** [comment]
Hello there and thanks for reaching out! 

The script **FockBasis_Example_1.m** makes use of the class defined by **FockBasis.m** and aims to familiarize the user with this type of class. It includes step-by-step examples where one can define a quantum state, add two quantum states, normalize them, displace a quantum state, and calculate and plot the Wigner distribution. 

All the scripts were developed on MATLAB 2023a (I updated the comments in the newest version. Thanks for pointing this out). I don't think you will have a problem running the scrips in MATLAB 2022b. 

As for the runtime of **FockBasis_Example_1.m** I can quote my comment from the old version of the script. 
At line ~ 120 
_N_hilbert = 20;                       % increase N_hilbert to get a better approximation, however, it gets slower !!
%  try N_hilbert = 10 15 20 25 30_ . 
So, to compare the Wigner function resolution versus runtime you can run the code with N_hilbert = 5 and N_hilbert = 10. In the first case, the code will be much faster (~ 15 seconds) but the plots will experience wiggling at the edges, while in the second case, the Wigner distributions will be closer to the analytical one (infinite Hilbert space) but the runtime will be longer (~ 30 seconds).  I have added more comments in the script header regarding this feature.   

Extra info: 
This long runtime is an issue only for the **FockBasis_Example_1.m** and **FockBasis.m**.  Calculating the Wigner distribution in Fock basis demands the calculation of associated Laguarre polynomials ( [see this](https://physics.stackexchange.com/questions/553225/representation-of-the-displacement-operator-in-number-basis) ). To calculate these polynomials one needs to compute their coefficients which are given by some Binomial coefficients. Binomial coefficients contain factorials that are very computationally demanding and thus the code becomes slow for large Hilbert spaces. It would be great if I could solve this problem, but the only thing I came up with is to calculate these coefficients in advance, store them in a matrix, and access each value when I am calculating the Wigner function. However, this is not enough. Let me know if you have any suggestions on that.

Filippos
